### PR TITLE
feat: use of MenuState for all NavigationTypes

### LINKED ISSUE #3968: [FEATURE] AddNavigationNode - set OpenInNewTab for more locations
**Is your feature request related to a problem? Please describe.**
So far there is no possibility to create footers whose links are opened in a new tab.

**Describe the solution you'd like**
An adaptation of the code so that nothing is changed in the cmdlets, but the menu definition is modified.

**Describe alternatives you've considered**
Retrieve the menu definition and save it back again is needed to enforce some properties of the menu to be shown, such as the audience targeting and OpenInNewTab functionality.
        

**Additional context**
Fixes #3232 
Related #2519

### PR DESCRIPTION
**Pull request by JuergenRB**
## Type ##
- [ ] Bug Fix
- [x] New Feature
- [ ] Sample

## Related Issues? ##
Fixes #3968
Related #3232

### CODE REVIEW

**Review by nils-a — APPROVED** [review]
LGTM!

**Comment by JuergenRB** [comment]
Solved Merge Conflict

**Comment by gautamdsheth** [comment]
@JuergenRB - did you fork the repository correctly ? I see no option to merge dev branch here .

**Comment by JuergenRB** [comment]
> @JuergenRB - did you fork the repository correctly ? I see no option to merge dev branch here .

@gautamdsheth  I have not done anything differently than usual.
I have now rebased with the current dev branch. I hope it works now

**Comment by gautamdsheth** [comment]
Thanks @JuergenRB , merged it !

**Pull request merged**
