### PR TITLE
Merge pull request #1 from pnp/dev

### PR DESCRIPTION
**Pull request by ToddKlindt**
Catch up.

Before creating a pull request, make sure that you have read the contribution file located at

https://github.com/pnp/powerShell/blob/dev/CONTRIBUTING.md

## Type ##
- [ ] Bug Fix
- [ ] New Feature
- [ ] Sample

## Related Issues? ##
Fixes #X, partially fixes #Y, mentioned in #Z, etc.

## What is in this Pull Request ? ##
Please describe the changes in the PR. 

### Guidance ###
* You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We use this as part of our release notes in monthly communications.*
* **Please target your PR to Dev branch. If you do not target the Dev branch we will not accept this PR.**

### CODE REVIEW

**Comment by ToddKlindt** [comment]
Catch up.

**Comment by gautamdsheth** [comment]
Hey @ToddKlindt - is this a work in progress ? Was it created by mistake, I don't see any files changed :)  ?

**Comment by erwinvanhunen** [comment]
Closing PR as no files in PR

**Comment by ToddKlindt** [comment]
Boo. I PRed in the wrong direction. I was trying to get my local repo back into sync. Nothing to see here.  Just an IT Pro screwing up GitHub. :)

**Pull request closed without merging**
