### PR TITLE
cmdlet for Restore-PnPDeletedcontainer. Closes #3623.

### LINKED ISSUE #3623: [FEATURE] New cmdlet for restore-pnpdeletedcontainer
A new cmdlet to allow to restore a deleted container. More info about the expected cmdlet can be found from the spo powershell corresponding cmdlet.
https://learn.microsoft.com/en-gb/powershell/module/sharepoint-online/restore-spodeletedcontainer?view=sharepoint-ps

Assign to me to work on it.

### PR DESCRIPTION
**Pull request by reshmee011**
## Type ##
- [ ] New Feature

## Related Issues? 
Closes #3623 

## What is in this Pull Request ? ##
New files
src\Commands\Admin\RestoreDeletedContainer.cs
documentation\Restore-PnPDeletedContainer.md

Updated file
documentation\Get-PnPDeletedContainer.md

### CODE REVIEW

**Comment by reshmee011** [comment]
@gautamdsheth : I have resolved the conflicts on the branch. Many thanks for your help on this too.

**Comment by gautamdsheth** [comment]
Can you please undo the changes in `version.txt` and `pnpframework_hash.txt` files ? I tried but somehow its not working , no idea why

**Comment by reshmee011** [comment]
@gautamdsheth , I have managed to remove the version.txt and pnpframework_hash.txt. Next time I will ensure there are no unnecessary files within the PR. Thanks for your help as usual.

**Comment by gautamdsheth** [comment]
Thanks @reshmee011 , merged it !!

Also, fixed the instances of SPO to PnP in docs 😊

**Pull request merged**
