### PR TITLE
Support document library owner to make change of the file version trim mode

### PR DESCRIPTION
**Pull request by msjennywu**
## Type ##
- [ ] Bug Fix
- [X] New Feature
- [ ] Sample

## Related Issues? ##
NA

## What is in this Pull Request ? ##
[FileVersion] Support document library owner to make change of the file version trim mode
1. Added 2 parameters "EnableAutoExpirationVersionTrim" and "ExpireVersionsAfterDays"
2. Added logic to update the doc lib trim mode by the values of the 2 new parameters
3. Updated the Set-PnPList.md file with description of the 2 new parameters and examples

### CODE REVIEW

**Comment by KoenZomers** [comment]
Thanks for contributing @msjennywu! I cannot get this compiled on my machine and as you can see, it also doesn't compile in the Git Actions process. Can you elaborate how you got the properties you're using? Perhaps a newer CSOM library version than we're using?

**Comment by msjennywu** [comment]
> Thanks for contributing @msjennywu! I cannot get this compiled on my machine and as you can see, it also doesn't compile in the Git Actions process. Can you elaborate how you got the properties you're using? Perhaps a newer CSOM library version than we're using?

**Comment by msjennywu** [comment]
> > Thanks for contributing @msjennywu! I cannot get this compiled on my machine and as you can see, it also doesn't compile in the Git Actions process. Can you elaborate how you got the properties you're using? Perhaps a newer CSOM library version than we're using?

@KoenZomers Thanks for the review! Yes, it uses new properties which is not in the published library yet. This is my first time to make the change here. I'm trying to send out review and get comments as earlier as possible. Please feel free to let me know if this PR impacts you guys or break anything. Thanks so much!

**Comment by KoenZomers** [comment]
Thanks for elaborating. Which CSOM library version did you compile this against and where did you get it from?

**Comment by msjennywu** [comment]
> Thanks for elaborating. Which CSOM library version did you compile this against and where did you get it from?

I use the dll that built in my local sharepoint repository. Replaced the one in nuget packages folder.
I renamed the properties to use the same name as the previous published properties.
I think the build will pass now. Please let me know if still any issue. Thanks!

**Comment by KoenZomers** [comment]
@msjennywu Its still unclear to me where you got the CSOM library from. I haven't heard yet that Microsoft was working on the functionality you're adding. Can you share more on where you got this from? It still doesn't build here nor in GitHub Actions.

**Comment by msjennywu** [comment]
> @msjennywu Its still unclear to me where you got the CSOM library from. I haven't heard yet that Microsoft was working on the functionality you're adding. Can you share more on where you got this from? It still doesn't build here nor in GitHub Actions.

Ah, my previous change is till not published I think. My CSOM change in Sharepoint is in build [16.0.23415.12000], but the published one here https://www.nuget.org/packages/Microsoft.SharePointOnline.CSOM is 16.0.23408.12000. Should I close my PR to unblock your building? And open it when my change is published? Please feel free to ping me (jennywu) on MS teams.

**Comment by VesaJuvonen** [comment]
These changes will be out with the CSOM release planned to get out in 31st of March. Let's double check the situation again then and move forward as needed.

**Comment by jackpoz** [comment]
I was very curious about this PR mentioned in the latest release notes. I couldn't find any documentation from CSOM about it but then SPO answered me when I tried to change these properties:
>Invoke-PnPQuery: The requested operation is part of a feature that is in private preview and will be available when the feature becomes generally available (GA).

Cool feature, can't wait for it to be GA 🚀

**Comment by KoenZomers** [comment]
Interesting feature indeed! More on this will be released in the near future.

**Pull request merged**
