### PR TITLE
Fix: Get-PnPField now returns specific field type

### PR DESCRIPTION
**Pull request by gautamdsheth**
## Type ##
- [x] Bug Fix
- [ ] New Feature
- [ ] Sample

## Related Issues? ##
NA

## What is in this Pull Request ? ##
Making the behavior consistent with the other parameters, `Get-PnPField`  now returns specific field type instead of the generic field when even List parameter is specified.

When using `Add-PnPField`, it was not working correctly for taxonomy types, it is now fixed.

### CODE REVIEW

**Comment by KoenZomers** [comment]
@gautamdsheth I understand why you're doing this, but I think this will create a non backwards compatible change, right?

**Comment by gautamdsheth** [comment]
Yeah unfortunately ☹

**Comment by KoenZomers** [comment]
@gautamdsheth I don't think it will be wise to break backwards compatibility with this. Would it be an idea to add a parameter -ReturnTyped which then would return the fields as typed fields and without this flag it would keep it as it is today?

**Comment by gautamdsheth** [comment]
Yeah , I can add that, no issues. Its just that it is inconsistent. If you dont specify the `-List` parameter, then it returns the typedValue, but if specify it returns a generic one. 

Totally agree, it might break backward compatibility, but adding is the additional param, should we really do that ??

**Comment by KoenZomers** [comment]
I don't really know another option. It's either that or do a non backwards compatible change.

**Comment by gautamdsheth** [comment]
@KoenZomers , changed the implementation :)

**Pull request merged**
