### PR TITLE
Some documentation fixes

### PR DESCRIPTION
**Pull request by PowershellScripts**
## Type ##
- [ ] Bug Fix
- [ ] New Feature
- [ ] Sample
- [x] Documentation

## Related Issues? ##
n/a

## What is in this Pull Request ? ##
* Added Connection parameter description
* Fixed \<tenant> to show correctly
* Added description to Description and Parameter
* Reordered parameters alphabetically 
* Corrected spelling to align with support.microsoft.com

### CODE REVIEW

**Comment by KoenZomers** [comment]
@PowershellScripts I tried rebasing this with dev as I was getting merge conflicts. This seems to have messed up your PR now. Sorry for that. If you still have your changes locally, could you create a new branch from it and push a new PR?

**Comment by PowershellScripts** [comment]
@KoenZomers  I will do that. No worries :)

**Comment by PowershellScripts** [comment]
@KoenZomers https://github.com/pnp/powershell/pull/3818

**Comment by KoenZomers** [comment]
Closing as it is merged through #3818

**Pull request closed without merging**
