### PR TITLE
Docs fixes and enhancements (adding missing descriptions) 

### LINKED ISSUE #2339: [BUG] documentation small bugs
### Reporting an Issue or Missing Feature
Hi, 👋. 
I love the way the docs are readable and organized on your site 👍. 
I created a small parser for them in order to create snippets json needed for a small and very simple VS Code extension I created. The script pointed the following issues:
- [Add-PnPFileToSiteTemplate](https://github.com/pnp/powershell/blob/dev/documentation/Add-PnPFileToSiteTemplate.md) - the description section is added twice. The first time is with PscalCase which probably should be all UPERCASE and the second section is emtpy - we should remove the second one and align the casing of the first one to be consistent with rest of the docs
- [Copy-PnPTeamsTeam](https://github.com/pnp/powershell/blob/dev/documentation/Copy-PnPTeamsTeam.md) - has wrong title, currently it is Copy-PnPList but should be Copy-PnPTeamsTeam

Also the following cmdlets have empty description section (It would be nice if at least one sentence would be added to explain what is possible with this command 🤔):
- Add-PnPApp
- Add-PnPAvailableSiteClassification
- Add-PnPAzureADGroupMember
- Add-PnPAzureADGroupOwner
- Add-PnPContentTypesFromContentTypeHub
- Add-PnPContentTypeToDocumentSet
- Add-PnPContentTypeToList
- Add-PnPDataRowsToSiteTemplate
- Add-PnPDocumentSet
- Add-PnPFieldFromXml
- Add-PnPFieldToContentType
- Add-PnPFolder
- Add-PnPGroupMember
- Add-PnPHtmlPublishingPageLayout
- Add-PnPIndexedProperty
- Add-PnPListDesign
- Add-PnPListFoldersToSiteTemplate
- Add-PnPListItem
- Add-PnPListItemComment
- Add-PnPMasterPage
- Add-PnPMicrosoft365GroupMember
- Add-PnPMicrosoft365GroupOwner
- Add-PnPOrgNewsSite
- Add-PnPPageSection
- Add-PnPPublishingImageRendition
- Add-PnPPublishingPage
- Add-PnPPublishingPageLayout
- Add-PnPSiteCollectionAppCatalog
- Add-PnPSiteDesign
- Add-PnPSiteDesignTask
- Add-PnPSiteScript
- Add-PnPSiteScriptPackage
- Add-PnPSiteTemplate
- Add-PnPTeamsChannel
- Add-PnPTeamsChannelUser
- Add-PnPTeamsTab
- Add-PnPTenantSequence
- Add-PnPTenantSequenceSite
- Add-PnPTenantSequenceSubSite
- Add-PnPView
- Add-PnPVivaConnectionsDashboardACE
- Add-PnPWebhookSubscription
- Add-PnPWebPartToWebPartPage
- Add-PnPWebPartToWikiPage
- Add-PnPWikiPage
- Clear-PnPAzureADGroupMember
- Clear-PnPAzureADGroupOwner
- Clear-PnPListItemAsRecord
- Clear-PnPMicrosoft365GroupMember
- Clear-PnPMicrosoft365GroupOwner
- Clear-PnPRecycleBinItem
- Clear-PnPTenantAppCatalogUrl
- Convert-PnPFolderToSiteTemplate
- Convert-PnPSiteTemplate
- Disable-PnPSiteClassification
- Enable-PnPFeature
- Enable-PnPSiteClassification
- Export-PnPListToSiteTemplate
- Export-PnPPage
- Export-PnPTaxonomy
- Export-PnPTermGroupToXml
- Find-PnPFile
- Get-PnPAlert
- Get-PnPApp
- Get-PnPAuditing
- Get-PnPAvailableLanguage
- Get-PnPAzureADGroup
- Get-PnPAzureADGroupMember
- Get-PnPAzureADGroupOwner
- Get-PnPAzureADUser
- Get-PnPAzureCertificate
- Get-PnPCompatibleHubContentTypes
- Get-PnPContentType
- Get-PnPContentTypePublishingHubUrl
- Get-PnPContentTypePublishingStatus
- Get-PnPDeletedMicrosoft365Group
- Get-PnPDocumentSetTemplate
- Get-PnPLabel
- Get-PnPListInformationRightsManagement
- Get-PnPListItem
- Get-PnPListItemAttachment
- Get-PnPListItemPermission
- Get-PnPListRecordDeclaration
- Get-PnPMasterPage
- Get-PnPMessageCenterAnnouncement
- Get-PnPMicrosoft365Group
- Get-PnPMicrosoft365GroupOwner
- Get-PnPMicrosoft365GroupSettings
- Get-PnPMicrosoft365GroupSettingTemplates
- Get-PnPNavigationNode
- Get-PnPOrgAssetsLibrary
- Get-PnPOrgNewsSite
- Get-PnPPropertyBag
- Get-PnPPublishingImageRendition
- Get-PnPRequestAccessEmails
- Get-PnPRoleDefinition
- Get-PnPSearchConfiguration
- Get-PnPSearchCrawlLog
- Get-PnPSearchSettings
- Get-PnPServiceCurrentHealth
- Get-PnPServiceHealthIssue
- Get-PnPSite
- Get-PnPSiteClosure
- Get-PnPSiteDesignRights
- Get-PnPSiteDesignRun
- Get-PnPSiteDesignRunStatus
- Get-PnPSiteDesignTask
- Get-PnPSitePolicy
- Get-PnPSiteScript
- Get-PnPSiteSearchQueryResults
- Get-PnPSiteTemplate
- Get-PnPStorageEntity
- Get-PnPSubWeb
- Get-PnPTaxonomySession
- Get-PnPTeamsApp
- Get-PnPTeamsChannel
- Get-PnPTeamsChannelFilesFolder
- Get-PnPTeamsChannelMessage
- Get-PnPTeamsChannelMessageReply
- Get-PnPTeamsChannelUser
- Get-PnPTeamsTab
- Get-PnPTeamsTeam
- Get-PnPTeamsUser
- Get-PnPTemporarilyDisableAppBar
- Get-PnPTenantAppCatalogUrl
- Get-PnPTenantId
- Get-PnPTenantInstance
- Get-PnPTenantSequence
- Get-PnPTenantSequenceSite
- Get-PnPTenantTemplate
- Get-PnPTermGroup
- Get-PnPTheme
- Get-PnPUnifiedAuditLog
- Get-PnPView
- Get-PnPVivaConnectionsDashboardACE
- Get-PnPWeb
- Get-PnPWebhookSubscriptions
- Get-PnPWebPartProperty
- Get-PnPWebPartXml
- Get-PnPWikiPageContent
- Grant-PnPHubSiteRights
- Grant-PnPSiteDesignRights
- Grant-PnPTenantServicePrincipalPermission
- Import-PnPTaxonomy
- Import-PnPTermGroupFromXml
- Install-PnPApp
- Invoke-PnPSiteTemplate
- Invoke-PnPTenantTemplate
- Invoke-PnPWebAction
- Measure-PnPList
- Measure-PnPWeb
- Move-PnPFolder
- Move-PnPListItemToRecycleBin
- Move-PnPRecycleBinItem
- New-PnPAzureADGroup
- New-PnPAzureCertificate
- New-PnPExtensibilityHandlerObject
- New-PnPList
- New-PnPMicrosoft365Group
- New-PnPMicrosoft365GroupSettings
- New-PnPSiteTemplate
- New-PnPSiteTemplateFromFolder
- New-PnPTeamsApp
- New-PnPTeamsTeam
- New-PnPTenantSequence
- New-PnPTenantSequenceCommunicationSite
- New-PnPTenantSequenceTeamNoGroupSite
- New-PnPTenantSequenceTeamNoGroupSubSite
- New-PnPTenantSequenceTeamSite
- New-PnPTenantTemplate
- New-PnPTermGroup
- New-PnPTermSet
- New-PnPUser
- New-PnPWeb
- Publish-PnPApp
- Publish-PnPContentType
- Read-PnPTenantTemplate
- Register-PnPAppCatalogSite
- Remove-PnPAlert
- Remove-PnPApp
- Remove-PnPAvailableSiteClassification
- Remove-PnPAzureADGroup
- Remove-PnPAzureADGroupMember
- Remove-PnPAzureADGroupOwner
- Remove-PnPContentType
- Remove-PnPContentTypeFromDocumentSet
- Remove-PnPContentTypeFromList
- Remove-PnPCustomAction
- Remove-PnPDeletedMicrosoft365Group
- Remove-PnPField
- Remove-PnPFieldFromContentType
- Remove-PnPFile
- Remove-PnPFileFromSiteTemplate
- Remove-PnPFolder
- Remove-PnPGraphSubscription
- Remove-PnPGroup
- Remove-PnPGroupMember
- Remove-PnPHomeSite
- Remove-PnPHubSiteAssociation
- Remove-PnPIndexedProperty
- Remove-PnPJavaScriptLink
- Remove-PnPKnowledgeHubSite
- Remove-PnPList
- Remove-PnPListDesign
- Remove-PnPListItem
- Remove-PnPListItemComment
- Remove-PnPMicrosoft365Group
- Remove-PnPMicrosoft365GroupMember
- Remove-PnPMicrosoft365GroupOwner
- Remove-PnPMicrosoft365GroupSettings
- Remove-PnPNavigationNode
- Remove-PnPPage
- Remove-PnPPublishingImageRendition
- Remove-PnPSiteGroup
- Remove-PnPStorageEntity
- Remove-PnPTeamsApp
- Remove-PnPTeamsChannel
- Remove-PnPTeamsChannelUser
- Remove-PnPTeamsTab
- Remove-PnPTeamsUser
- Remove-PnPView
- Remove-PnPVivaConnectionsDashboardACE
- Remove-PnPWebhookSubscription
- Remove-PnPWebPart
- Rename-PnPFile
- Rename-PnPFolder
- Request-PnPReIndexList
- Reset-PnPFileVersion
- Reset-PnPMicrosoft365GroupExpiration
- Restore-PnPDeletedMicrosoft365Group
- Revoke-PnPHubSiteRights
- Save-PnPSiteTemplate
- Send-PnPMail
- Set-PnPAppSideLoading
- Set-PnPAuditing
- Set-PnPDefaultContentTypeToList
- Set-PnPDefaultPageLayout
- Set-PnPDocumentSetField
- Set-PnPField
- Set-PnPFileCheckedOut
- Set-PnPGraphSubscription
- Set-PnPHomePage
- Set-PnPHomeSite
- Set-PnPKnowledgeHubSite
- Set-PnPListItem
- Set-PnPListItemAsRecord
- Set-PnPListItemPermission
- Set-PnPMessageCenterAnnouncementAsArchived
- Set-PnPMessageCenterAnnouncementAsFavorite
- Set-PnPMessageCenterAnnouncementAsNotArchived
- Set-PnPMessageCenterAnnouncementAsNotFavorite
- Set-PnPMessageCenterAnnouncementAsRead
- Set-PnPMicrosoft365Group
- Set-PnPMicrosoft365GroupSettings
- Set-PnPSearchSettings
- Set-PnPSite
- Set-PnPSiteClosure
- Set-PnPSiteDesign
- Set-PnPSitePolicy
- Set-PnPSiteScriptPackage
- Set-PnPSiteTemplateMetadata
- Set-PnPStorageEntity
- Set-PnPTaxonomyFieldValue
- Set-PnPTeamsChannel
- Set-PnPTeamsChannelUser
- Set-PnPTeamsTab
- Set-PnPTeamsTeam
- Set-PnPTeamsTeamArchivedState
- Set-PnPTemporarilyDisableAppBar
- Set-PnPWebhookSubscription
- Set-PnPWebPartProperty
- Submit-PnPSearchQuery
- Submit-PnPTeamsChannelMessage
- Sync-PnPAppToTeams
- Test-PnPListItemIsRecord
- Test-PnPTenantTemplate
- Uninstall-PnPApp
- Unpublish-PnPApp
- Unpublish-PnPContentType
- Unregister-PnPHubSite
- Update-PnPApp
- Update-PnPTeamsApp
- Update-PnPVivaConnectionsDashboardACE

### PR DESCRIPTION
**Pull request by Adam-it**
## Type ##

- [X] Bug Fix
- [ ] New Feature
- [ ] Sample

## Related Issues? ##

Fixes #2339

## What is in this Pull Request ? ##

The aim of this PR is to add missing descriptions in some commands and small docs fixes that are mentioned in the related issue.

### CODE REVIEW

**Comment by KoenZomers** [comment]
Amazing work, thanks @Adam-it !

**Comment by Adam-it** [comment]
> Amazing work, thanks @Adam-it !

@KoenZomers does this repo participate in Hacktoberfest? I see you have 'hacktoberfest' topic added. Shouldn't this PR count as well 😉?
If so please add the 'hacktoberfest-accepted' label to it.

**Comment by KoenZomers** [comment]
Sure thing @Adam-it, here you go, you deserve it for such a contribution! :)

**Comment by gautamdsheth** [comment]
@Adam-it - done, no bother 😊

I guess since Koen approved/reviewed the PR, it will be automatically considered since the library is tagged already. 

We don't need to add labels to PR.
In my case, check this image:

image

These are for 2 PRs:

https://github.com/pnp/powershell/pull/2407

and 

https://github.com/pnp/powershell/pull/2406

Both of them are considered as accepted since somebody reviewed and added it.
As long as the repo is tagged with hacktoberfest and somebody approves the PR, it will be considered . Atleast that's what I think,I could be wrong :)

**Comment by Adam-it** [comment]
cool. thanks for your help 👍. You rock 🤩

**Comment by gautamdsheth** [comment]
Umm, I am ok, you rock 🙏😍

**Pull request merged**
