### PR TITLE
Additional tenant settings from api/SPOInternalUseOnly.TenantAdminSettings

### PR DESCRIPTION
**Pull request by reshmee011**
Before creating a pull request, make sure that you have read the contribution file located at

There are additional settings available from  https://contoso-admin.sharepoint.com/_api/SPOInternalUseOnly.TenantAdminSettings. Adding those to Get-PnPTenant will make it easier to retrieve these properties for governance or inventory purposes. 

Original idea was from Tobias Maestrini and I helped implement the retrieval of these properties.

## Type ##
Three new files to support the cmdlet 
documentation\Get-PnPTenantInternalSetting.md
src\Commands\Model\SPOTenantInternalSetting.cs
src\Commands\Admin\GetTenantInternalSetting.cs

## What is in this Pull Request ? ##
Additional tenant properties available from /_api/SPOInternalUseOnly.TenantAdminSettings

### CODE REVIEW

**Comment by tmaestrini** [comment]
Hey @reshmee011, thank you very much for your support! :) See my PN in X chat regarding this. 💪

**Comment by reshmee011** [comment]
Sorry accidentally closed while trying to fix the build issues and refactoring the code to be a separate cmdlet instead

**Comment by reshmee011** [comment]
@gautamdsheth : I have update it to be singular internalsetting. Thanks for the review.

**Review by gautamdsheth — CHANGES_REQUESTED** [review]
Sorry, one more change ! 
Need to replace `Newtonsoft.Json` with `System.Text.Json`, let me know if you need help.

**Comment by reshmee011** [comment]
@gautamdsheth : I have updated to use "System.Text.Json;". Thanks very much for the review.

**Comment by gautamdsheth** [comment]
Merged it , thank you!!

**Pull request merged**
