### PR TITLE
Updates to Add/Get/RemoveEventReceiver cmdlets

### LINKED ISSUE #241: Add SiteCollection as scope to EventReceivers cmdlets
**Is your feature request related to a problem? Please describe.**
*-PnPEventReceiver cmdlets currently only support List or Web scopes. It would be wonderful to have Site as another scope to get site collection level event receivers.

**Describe the solution you'd like**
```Get-PnPEventReceiver -Scope Site``` or something like that.

**Describe alternatives you've considered**
I currently use CSOM to work with site collection level event receivers.
```
$clientContext = Get-PnPContext
$site = $clientContext.Site; 
$clientContext.Load($site)
$eventReceivers = $site.EventReceivers
$clientContext.Load($eventReceivers)
Invoke-PNPQuery
```
**Additional context**

### PR DESCRIPTION
**Pull request by bhishma**
Before creating a pull request, make sure that you have read the contribution file located at

https://github.com/pnp/powerShell/blob/dev/CONTRIBUTING.md

## Type ##
- [ ] Bug Fix
- [x ] New Feature
- [ ] Sample

## Related Issues? ##
Fixes #241

## What is in this Pull Request ? ##
Updated Add/Get/RemoveEventReceiver cmdlets to allow Site Collection as an option. Currently these cmdlets only allow List or Web. 
It depends on an update to PnPFramework. See : https://github.com/pnp/pnpframework/pull/166

### CODE REVIEW

**Comment by erwinvanhunen** [comment]
Hi!

Thank you for your work, but unfortunately there are some problems with this PR which prevents us from merging it. The GetEventreceiver.cs class for instance references to a ParameterSet called "Site", but it's not defined, so it will never resolve to that.

In the AddEventReceiver.cs you define a SitePipeBind class called site, but you're not using the value, other than checking if it has been specified. That's not how to use a SitePipeBind as that one requires a value in order to be used, E.g. `-Site https://mysiteurl`. Maybe you meant to use a SwitchParameter instead?

Using SitePipeBind would mean people can provide a different url, but you're not resolving it, as you're using ClientContext.Site. The cmdlets will not automatically switch the context based upon the site provided in the SitePipeBind.

Overal: it is very important to make sure that the cmdlets will continue to work as they did before the change, with exactly the same parameters. Otherwise this would be a breaking change and those we only allow in major releases.

**Comment by bhishma** [comment]
Thank you so much for the explanation. SwitchParameter makes a lot more sense as to what I was expecting. Add-PnPEventReceiver has dependency on SiteExtensions in pnpframework.

**Comment by erwinvanhunen** [comment]
Hi,

There is still a problem with the logic in the cmdlet as you propose it. You specify the -Site parameter now as a switch parameter, but it is available for all parameter sets. This means you could theoretically do:

```powershell
Get-PnPEventReceiver -List "mylist" -Site -Identity $identity
```

That does not make much sense... what would be the expected outcome? 

Have a look here for more information about ParameterSets. https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/cmdlet-parameter-sets?view=powershell-7.1

**Comment by bhishma** [comment]
Added another ParameterSet but made ListPipeBind List mandatory on List ParameterSet to resolve ambiguity. Existing functionality still works
Still dependent on https://github.com/pnp/pnpframework/pull/166

**Comment by KoenZomers** [comment]
I'll fix this PR so it works well. Already updated the Add and Get methods. Still need to do the Remove. I will push it out to a new PR once done. I'll therefore close this PR.

Thanks @bhishma for your efforts!

**Comment by KoenZomers** [comment]
Reference to the new PR branch: https://github.com/KoenZomers/pnppowershellcore/tree/PR250

**Pull request closed without merging**
