### PR TITLE
Update Add-PnPTeamsTab.md issue #2844

### PR DESCRIPTION
**Pull request by kasperbolarsen**
added example for creating a Planner tab

Before creating a pull request, make sure that you have read the contribution file located at

https://github.com/pnp/powerShell/blob/dev/CONTRIBUTING.md

## Type ##
- [ ] Bug Fix
- [ ] New Feature
- [X ] Sample

## Related Issues? ##
None
## What is in this Pull Request ? ##
Added sample for Planner tab

### CODE REVIEW

**Comment by gautamdsheth** [comment]
Hey @kasperbolarsen - I guess it would make sense if we make the `ContentUrl` parameter available for `-Planner` type Teams tab , is that correct ?

**Comment by kasperbolarsen** [comment]
Hi @gautamdsheth 

Yeah, that would be nice but it is not urgent as the -type Custom workaround works fine

**Comment by gautamdsheth** [comment]
hi @kasperbolarsen , just made the `-ContentUrl` parameter available for Planner Teams tab type. 
Will be available in tomorrow's nightly.

Can you please update the docs to use that ?  Also, can you change `tcwlv.onmicrosoft.com` to `contoso.onmicrosoft.com` or something like this:

```
$tenant = "contoso.onmicrosoft.com"
$teamsTab = Add-PnPTeamsTab -Team $groupId -Channel $teamsChannel -DisplayName "test1" -Type Custom -TeamsAppId "com.microsoft.teamspace.tab.planner" -Connection $conn -ContentUrl "https://tasks.office.com/$tenant/Home/PlannerFrame?page=7&planId=$($PlannerPlan.Id)"
```

Will help other folks in who copy paste docs to  make changes easily 
Sorry for inconvenience, but also thanks for pointing it 😞🙏

**Comment by kasperbolarsen** [comment]
Hi @gautamdsheth 

Sure, will do.

The TeamsAppId argument should not be used with the updated Add-PnPTeamsTab -Type Planner command,  right?

**Comment by gautamdsheth** [comment]
@kasperbolarsen  - correct. It will not needed when using `-Planner` type tab.

**Pull request closed without merging**
