### PR TITLE
Changed scriptErrorsSuppressed to false

### PR DESCRIPTION
**Pull request by mikevasiloff**
## Type ##
- [X] Bug Fix
- [ ] New Feature
- [ ] Sample

## Related Issues? ##
Addresses bug #1706 so that the pop-up browser authentication window can display the PKI/client certificate selection window.

## What is in this Pull Request ? ##
Single change to the src/Commands/Utilities/BrowserHelper.cs file, [line 27](https://github.com/pnp/powershell/blob/dev/src/Commands/Utilities/BrowserHelper.cs#L27) changing the GetWebLoginClientContext function function so that the default value for scriptErrorsSuppressed is `false`.

### CODE REVIEW

**Comment by KoenZomers** [comment]
Thanks for your contribution and detailed repro steps @mikevasiloff . I believe to remember from firsthand that the errors are being suppressed as at least previously it could happen a lot that the old Internet Explorer container would not be able to handle parts of the login pages very well and would throw several JavaScript error dialog boxes when trying to log on. Not sure if that's still the case today. When testing with your PR branch against my normal tenant, I did not get any errors anymore, so I guess we're good with this change if that helps in your scenario.

One thing I'm wondering though, you're mentioning the issue you're facing applies to both UseWebLogin and Interactive. These are both completely different implementations. Only the first would be affected by the change you propose, so I don't see how the Interactive login would be fixed by this. Have you tested this and are you sure this is the case?

**Comment by mikevasiloff** [comment]
@KoenZomers, you're very welcome.  Ok that makes sense, thanks for the background info.

As for `-Interactive`, I'll have to double check as I thought I tested both.  For the National Clouds we have to register our own app in Azure AD for "PnP PowerShell" and then specify the `-ClientId`, `-Tenant`, and `-AzureEnvironment` when making a connection which still opens the same user PKI/client certificate selection window.

**Comment by KoenZomers** [comment]
Please check indeed if interactive works okay as well or needs additional fixing. Weblogin is an old method which only provides access to the SharePoint API and not any of the countless other APIs behind many of the cmdlets so best would be if interactive or devicelogin will work for your scenario.

**Comment by mikevasiloff** [comment]
@KoenZomers, I completely understand about the limitations of the `-UseWebLogin` option, it's just that in the Sovereign Clouds it can be hard to convince customers to register PnP to enable the `-Interactive` method.  After looking at this again you are right that even with the change I proposed that helps the `-UseWebLogin` case, it didn't affect the `-Interactive` case.  When using `-Interactive` it exhibited the same behavior as documented in bug #1706 where the authentication pop-up window just "freezes" rather than providing the ability to select the PKI/client certificate.  Unfortunately, I'm not familiar enough with the code to know which function relates to the `-Interactive` parameter.

**Comment by mikevasiloff** [comment]
Actually, looking at your change to the PnPConnection.cs file I noticed `CreateWithInteractiveLogin` with a call to the `PnP.Framework.AuthenticationManager.CreateWithInteractiveLogin` function.  So it looks like this is using a PnP Framework method.  This then lead me to the [PnP.Framework/AuthenticationManager.cs](https://github.com/pnp/pnpframework/blob/dev/src/lib/PnP.Framework/AuthenticationManager.cs) file where I see `WithCustomWebUi` being called, but I can't seem to find the source for that.  If this is ultimately coming from the PnP Framework instead, does that mean I need to open a bug in that repo for the `-Interactive` part of this issue?

**Comment by KoenZomers** [comment]
Would have to dive into the code to be 100% sure but I believe it's actually MSAL that is being utilized for interactive and devicelogin. Have you tried your success with devicelogin? This allows you to use any browser thus is not dependant on possible limitations by any framework.

**Comment by KoenZomers** [comment]
As we're going to do a new release of PnP PowerShell any time now, I will proceed with merging this PR so it will be included in this next release. If any further work needs doing to accommodate other authentication methods for making use of certificates, please file a new PR and we can take it from there.

**Pull request merged**
