### PR TITLE
Added `-DefaultSensitivityLabelForLibrary` to `Set-PnPList`

### PR DESCRIPTION
**Pull request by KoenZomers**
## Type ##
- [ ] Bug Fix
- [X] New Feature
- [ ] Sample

## Related Issues? ##
N/A

## What is in this Pull Request ? ##
Added `-DefaultSensitivityLabelForLibrary` to `Set-PnPList` which allows setting the default sensitivity label for a library

### CODE REVIEW

**Comment by NaveenRajdev** [comment]
Hello @KoenZomers 

I am trying to use the above command but it says

Set-PnPList : A parameter cannot be found that matches parameter name 'DefaultSensitivityLabelForLibrary'.

I have update the module to the latest. Could you please tell me what I am doing wrong.

Thanks

**Comment by KoenZomers** [comment]
@NaveenRajdev Update to the latest nightly release using Update-Module PnP.PowerShell -AllowPrerelease

**Comment by NaveenRajdev** [comment]
I ran the updated command and it still gives me the error. Could you please let me know what the next step I can follow is to accommodate the same?

Naveen Rajdev
E
***@***.******@***.***>
M
+61 470 254 804
P
1300 835 723
velrada.com<https://velrada.com/>

**Comment by jfmathieu** [comment]
Hi Naveen,
I make it work with the build 2.0.35.
It work. If you call the fonction with the name you will need to be Conformity Administrator to get the GUID automaticly.
If you call it with the GUID directly, it will work with lower priviledge.
Thanks

**Pull request merged**
