### PR TITLE
Unblock connection to SharePoint 2013

### LINKED ISSUE #4609: Connect-PnPOnline - On Prem Tranformation
When connecting to SharePoint 2013 with latest PnP version (2.12.0)

I am getting 
"Connect-PnPOnline: Specified method is not supported."

Example: 
$sp13Conn = Connect-PnPOnline -Url http://portal2013/en -Credentials OnPrem -ReturnConnection -TransformationOnPrem

image

Note: https://github.com/pnp/powershell/blob/572d6973cfd98144cb720df03e5f00e9b4f57178/src/Commands/Base/PnPConnection.cs#L455

Please assign to me :-) I have a test rig back operational to investigate transform issues.

### PR DESCRIPTION
**Pull request by pkbullock**
Transformation On Prem flag added

Before creating a pull request, make sure that you have read the contribution file located at

https://github.com/pnp/powerShell/blob/dev/CONTRIBUTING.md

## Type ##
- [X] Bug Fix
- [ ] New Feature
- [ ] Sample

## Related Issues? ##
Fixes #4609 

## What is in this Pull Request ? ##

Flag to bypass client id check on transformation on-premises.

Tested with SP2013

### CODE REVIEW

**Comment by pkbullock** [comment]
Not sure why this is failing here, but fine on my local machine. I've only changed one line lol. Am i missing something?

**Comment by pkbullock** [comment]
@gautamdsheth - this is most odd. Still fails.

**Comment by pkbullock** [comment]
@gautamdsheth - I'm stuck here, is there a dependency I am missing in GitHub, seems like it cannot build due to a missing Graph dependency. The only change I have made to this PR is one line, Boolean check which doesn't change any Graph dependencies. All local builds work.

**Comment by gautamdsheth** [comment]
@pkbullock - yeah, must be something weird with the GH action. Tested it locally, builds fine, merged it. Thank you !

**Comment by pkbullock** [comment]
Awesome, thank you @gautamdsheth

**Pull request merged**
