### PR TITLE
Updated documentation for Get-PnPFlowrun, which includes samples on how to get specific flowrun trigger information

### PR DESCRIPTION
**Pull request by NishkalankBezawada**
## Type ##
- [ ] Bug Fix
- [ ] New Feature
- [ ] Sample

## Related Issues? ##
Fixes #X, partially fixes #Y, mentioned in #Z, etc.

## What is in this Pull Request ? ##
Updated documentation for Get-PnPFlowrun, which includes samples on how to get specific flowrun trigger information. 

The samples are as below,

### New Example 
```powershell
$environment = Get-PnPPowerPlatformEnvironment
$flowrun = Get-PnPFlowRun -Environment $environment -Flow fba63225-baf9-4d76-86a1-1b42c917a182 -Identity 08585531682024670884771461819CU230
$flowrun.Properties.trigger
```
This returns a specific flow run trigger information as below

```powershell
Name              : Recurrence
StartTime         : 2024-02-02 06:00:00
EndTime           : 2024-02-02 06:00:00
ScheduledTime     : 2024-02-02 06:00:00
OriginHistoryName : 08584947532854535568834568113CU171
Code              : OK
Status            : Succeeded
```

### New Example 
```powershell
$environment = Get-PnPPowerPlatformEnvironment
$flowruns = Get-PnPFlowRun -Environment $environment -Flow fba63225-baf9-4d76-86a1-1b42c917a182
$flowruns.Properties.trigger
```
This returns a specific flows trigger information as below

```powershell
Name              : Recurrence
StartTime         : 2024-02-02 06:00:00
EndTime           : 2024-02-02 06:00:00
ScheduledTime     : 2024-02-02 06:00:00
OriginHistoryName : 08584947532854535568834568113CU171
Code              : OK
Status            : Succeeded

Name              : Recurrence
StartTime         : 2024-02-01 06:00:00
EndTime           : 2024-02-01 06:00:00
ScheduledTime     : 2024-02-01 06:00:00
OriginHistoryName : 08584948396849679000001446214CU251
Code              : OK
Status            : Succeeded

Name              : Recurrence
StartTime         : 2024-01-31 06:00:00
EndTime           : 2024-01-31 06:00:00
ScheduledTime     : 2024-01-31 06:00:00
OriginHistoryName : 08584949260853628013416159080CU185
Code              : OK
Status            : Succeeded
```

Thanks,
Nishkalank Bezawada

### CODE REVIEW

**Comment by KoenZomers** [comment]
Thanks @NishkalankBezawada !

**Comment by NishkalankBezawada** [comment]
> Thanks @NishkalankBezawada !

Many Thanks @KoenZomers & @gautamdsheth for your support 😇😊

**Comment by vishalgoyal2472** [comment]
When I am using `Get-PnPFlowRun -Environment $environment -Flow $flow.Name` comamand its thorwing below error and its happening after 9 September when we switched to Single Tenant.

> Get-PnPFlowRun: AADSTS65001: The user or administrator has not consented to use the app
> lication with ID '**********************' named 'PnP PowerShell App Singl
> e Tenant'. Send an interactive authorization request for this user and resource. Trace
> ID: ******************* Correlation ID: ************************ Timestamp: 2024-09-24 11:55:08Z

**Our azure admin want to know which permission it needs because in below article its written that it needs 
management.azure.com permission but there is no such type of permission**

https://pnp.github.io/powershell/cmdlets/Get-PnPFlowRun.html   


**Note**-Service account have below azure permissions

image

**Comment by KoenZomers** [comment]
Hi @vishalgoyal2472 have you seen this table? Does that help?
https://pnp.github.io/powershell/articles/determinepermissions.html#help-i-cant-figure-out-which-permissions-i-need

**Comment by vishalgoyal2472** [comment]
> Hi @vishalgoyal2472 have you seen this table? Does that help? https://pnp.github.io/powershell/articles/determinepermissions.html#help-i-cant-figure-out-which-permissions-i-need

Yes it worked, thank you!!

**Pull request merged**
