### PR TITLE
new cmdlet for Add-PnPTenantRestrictedSearchAllowedList

### PR DESCRIPTION
**Pull request by reshmee011**
## Type ##
- [ ] New Feature

## What is in this Pull Request ? ##
Files to support new cmdlet for Add-PnPTenantRestrictedSearchAllowedList

documentation\Add-PnPTenantRestrictedSearchAllowedList.md
src\Commands\Admin\AddTenantRestrictedSearchAllowedList.cs

### CODE REVIEW

**Comment by KoenZomers** [comment]
Thanks @reshmee011 . It feels like a paramset would be a better fit here as opposed to using Dynamic Parameters. Would you agree or is there a specific reason you chose to go with this option?

**Comment by reshmee011** [comment]
@KoenZomers : Hello, it makes more sense to use paramset to be consistent and easier to maintain in the future. I will refactor the code.

**Comment by reshmee011** [comment]
@KoenZomers : I have updated the cmdlet to use parameter set, thanks very much for the review.

**Comment by KoenZomers** [comment]
Thanks @reshmee011 !

**Pull request merged**
