### PR TITLE
Update Set-PnPInPlaceRecordsManagement.md

### PR DESCRIPTION
**Pull request by PowershellScripts**
## Type ##
- [ ] Bug Fix
- [ ] New Feature
- [ ] Sample
- [x] Parameter description

## Related Issues? ##
N/A

## What is in this Pull Request ? ##
* Cmdlet description
* Parameter description

### CODE REVIEW

**Comment by PowershellScripts** [comment]
@KoenZomers The parameters should be in alphabetic order, right? Did I understand it correctly?

**Comment by KoenZomers** [comment]
@PowershellScripts For now we have decided to not set any guidance for this. You may put them in the order you feel makes most sense :)

**Comment by PowershellScripts** [comment]
Understood. I will then mainly leave them be in the order they are now. Only if I see somewhere something odd or out of place, I will go for rearranging.

**Comment by KoenZomers** [comment]
Perfect, thanks for your efforts in updating the documentation!

**Pull request merged**
