### PR TITLE
GetSiteSearchQueryResults: fix 'Value cannot be null' exception

### PR DESCRIPTION
**Pull request by fowl2**
## Type ##
- [X] Bug Fix

## Related Issues? ##
Fixes #2130

### Repro

1. Connect to a site using `Connect-PnPOnline`
2. Run `Get-PnPSiteSearchQueryResults`

This exception occurs:

```
Message          : Value cannot be null.
                   Parameter name: context
Stacktrace       :    at Microsoft.SharePoint.Client.ObjectPath..ctor(ClientRuntimeContext context, ObjectPath 
                   parent, Boolean addToContext)
                      at Microsoft.SharePoint.Client.ObjectPathConstructor..ctor(ClientRuntimeContext context, 
                   String typeId, Object[] parameters)
                      at Microsoft.SharePoint.Client.Search.Query.KeywordQuery..ctor(ClientRuntimeContext 
                   context)
                      at PnP.PowerShell.Commands.Search.SubmitSearchQuery.CreateKeywordQuery(String 
                   clientFunction)
                      at PnP.PowerShell.Commands.Search.SubmitSearchQuery.Run()
                      at PnP.PowerShell.Commands.Search.GetSiteSearchQueryResults.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()

```

I'm honestly not sure how this cmdlet ever worked without passing the connection. I've had a quick look through the commit history and see nothing obvious.

## What is in this Pull Request ? ##
Pass the connection from the parent cmdlet to the child cmdlet, so that it can access the ClientContext.

### CODE REVIEW

**Comment by KoenZomers** [comment]
Thanks @fowl2 !

**Comment by IfEyeOnlyKnew** [comment]
Just checking, but would this change show up in the latest version? If so, the I am seeing the same error message with this version. Thanks for your support.

ModuleType        Version      Name                                                                                                                                 
----------               -------      ----                                                                                                         
Manifest               1.11.7       PnP.PowerShell

**Comment by KoenZomers** [comment]
It should be in the latest nightly build indeed. It showing on prem results can only be reasoned based on the information provided that you're having a cloud search service application enabled on your on prem farm which is sending its index to spo. If that's the case, then this is expected behavior.

**Comment by thaiphv** [comment]
Can this be released as a new release? My company's Proget feed only clones non-nightly releases.

**Pull request merged**
