### PR TITLE
Adding VivaConnectionsDefaultStart option to SetHomeSite

### PR DESCRIPTION
**Pull request by reshmee011**
Before creating a pull request, make sure that you have read the contribution file located at

https://github.com/pnp/powerShell/blob/dev/CONTRIBUTING.md

## Type ##
- [ ] New Feature

## What is in this Pull Request ? ##
Adding ability to set VivaConnectionsDefaultStart

### CODE REVIEW

**Comment by gautamdsheth** [comment]
Awesome stuff @reshmee011 , just 2 comments :) 

1) Can you please move the executequery outside if/else condition like this ?

```
if(){
// code
}
else{
// more code
}

ClientContext.ExecuteQueryRetry();
```

2) Can you also please update the related docs for this ? It is located in docs folder `(docs > set-pnphomesite.md)`

Also, @anoopt , dont work on this now 🤣😭

**Comment by reshmee011** [comment]
@gautamdsheth : thanks for the prompt review, I need to remember about updating docs in the future. @anoopt : hope you have not worked on it yet.  @gautamdsheth : for any new features, shall I raise it as an issue first before I start working on it?

**Comment by reshmee011** [comment]
@gautamdsheth , bool will allow to pass $true or $false to toggle on and off the viva experience to the Home Site, switch parameter does not give that ability.

**Comment by gautamdsheth** [comment]
We can set the value when using SwitchParameter 😊

Like this:

```
-VivaConnectionsDefaultStart ---> sets value to true

or

-VivaConnectionsDefaultStart:$false ---> sets value to false

or 

-VivaConnectionsDefaultStart:$true ---> set value to true. Not necessarily needed because if the parameter is specified, then it is true.
```

You can check this example:

https://pnp.github.io/powershell/cmdlets/Enable-PnPPowerShellTelemetry.html

We are using `-Force` as a switch parameter.

**Comment by reshmee011** [comment]
@gautamdsheth : Awesome, thanks for the example how to use the switchparameter to turn on and off. I did not think about it. Happy to keep it as switch parameter. Shall I make updates to the code and docs to revert the VivaConnectionsDefaultStart to switch parameter. ?

**Comment by gautamdsheth** [comment]
Yes please 😊

**Comment by reshmee011** [comment]
@gautamdsheth : I have reverted the parameter to be switch parameter and amended the get-pnphomesite to return its value with an additional parameter.

**Comment by gautamdsheth** [comment]
Thank you, merged it !

**Pull request merged**
