### PR TITLE
New command Get-PnPPowerApp

### PR DESCRIPTION
**Pull request by siddharth-vaghasia**
## Type ##
- [ ] New Feature

## What is in this Pull Request? ##
Added new command to get the list of Power Apps from the environment, also support for getting specific Power App by passing Identify as a parameter.

Note - Doing PR here for the first time, so all the code review comments are welcome.....

### Guidance ###
* You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We use this as part of our release notes in monthly communications.*
* **Please target your PR to Dev branch. If you do not target the Dev branch we will not accept this PR.**

### CODE REVIEW

**Comment by gautamdsheth** [comment]
Hi @siddharth-vaghasia , amazing stuff. Really glad to see you contribute here 😊

Have a few comments :) 

Does `Get-PnPPowerAutomateApp` or `Get-PnPPowerPlatformApp` make it more clear ? Maybe we can use that.

Can you please capitalize the properties in the `PowerApp.cs` ? 

The file `PowerAppProperties.cs` contains a bunch of classes in the single file , can you please make them as separate files ?

**Comment by siddharth-vaghasia** [comment]
Hey @gautamdsheth - thanks for reviewing.... please find comments inline

Does Get-PnPPowerAutomateApp or Get-PnPPowerPlatformApp make it more clear? Maybe we can use that.
[Comment] - Actually in general terms we call it PowerApp.... PowerPlatform is a broader term that has PowerApps, PowerAutomat, and PowerBI as products within.... to keep it consistent with Get-PnPFlow like I have kept it as Get-PnPPowerApp because PowerApp is other product with same suite of products...Also same is the name of a command in PowerApps Powershell. Get-PowerApp.. let me know your thoughts.

Can you please capitalize the properties in the PowerApp.cs ?
[Comment] - working on this
The file PowerAppProperties.cs contains a bunch of classes in the single file , can you please make them as separate files ?
[Comment] - working on this

**Comment by gautamdsheth** [comment]
@siddharth-vaghasia  - let me know whenever the API or authentication is stable enough, will take a look then, keeping it open for now :)

**Comment by KoenZomers** [comment]
Any updates on this @siddharth-vaghasia ?

**Comment by siddharth-vaghasia** [comment]
Hi @KoenZomers - I am waiting for to know final scope to be added ton PnP App Registration, it is tracked here
https://github.com/pnp/cli-microsoft365/pull/4460

**Comment by siddharth-vaghasia** [comment]
Hey @gautamdsheth @KoenZomers - Seems the API is working again now and tested it, can you please verify

image

image

**Pull request merged**
