### PR TITLE
Feature/exclude deprecated terms

### PR DESCRIPTION
**Pull request by sankarkumar23**
Before creating a pull request, make sure that you have read the contribution file located at

https://github.com/pnp/powerShell/blob/dev/CONTRIBUTING.md

## Type ##
- [ ] Bug Fix
- [x] New Feature
- [ ] Sample

## Related Issues? ##
Fixes #X, partially fixes #Y, mentioned in #Z, etc.

## What is in this Pull Request ? ##
Added additional parameter to exclude deprecated terms

### CODE REVIEW

**Comment by markgort86** [comment]
I think it's also a good idea to add some additional details about for this PR. See: https://pnp.github.io/powershell/articles/gettingstartedcontributing.html

**Comment by KoenZomers** [comment]
Thanks @sankarkumar23 for your contribution. I checked your PR. The way its currently written, it will only work if providing a -TermsetId. I was wondering if there was a specific reason why you didn't add the -ExcludeDeprecated parameter to the TermSet parametergroup. Now it looks like it will also work with it, but it doesn't. I have updated your PR so it's only set to that paramset.

If I missed some thoughts here why this would not be okay, let me know.

**Comment by sankarkumar23** [comment]
Agree with your comments. I prepared this code a year ago when I had the same need. I was new to GitHub and didn't understand how to push a PR until markgrot86 tapped me a few weeks ago. Now, I've moved away from the SharePoint platform and can't recollect what all I missed. You can take the code if you find it useful create a new branch and push it, as I no longer have the environment to test it. This experience really helped me learn how to contribute to open source code. 
You can delete my PR if needed.

**Comment by KoenZomers** [comment]
Thanks for elaborating @sankarkumar23 . I think we're good to go for a merge on this one then. I'll do a final review and test in the next days and if all works well, I'll merge it.

**Comment by KoenZomers** [comment]
Thanks @sankarkumar23 for your contribution!

**Pull request merged**
