### PR TITLE
Update set-pnpfield with no crawl to prevent the field from being returned in search results

### PR DESCRIPTION
**Pull request by reshmee011**
## Type ##
- [ ] New Feature

## What is in this Pull Request ? ##
Add no crawl property to set-pnpfield Update set-pnpfield to prevent the field from being returned in search results

### CODE REVIEW

**Comment by reshmee011** [comment]
@gautamdsheth : I have updated the docs. Forgot to push the changes for the docs earlier..

**Comment by gautamdsheth** [comment]
@reshmee011 - do we really need this ? I mean , we can easily do it via something like this. 
Works for almost all properties.

```
Set-PnPField -Identity "Test" -Values @{NoCrawl=$true}
```

**Comment by reshmee011** [comment]
@gautamdsheth , updating NoCrawl property is failing using method  -values @{NoCrawl=$true}  as well the switchparameter -nocrawl.

image

Something changed to prevent the update to the NoCrawl at column level. I will raise it with Microsoft and wait for an answer. 

Happy for the PR to be closed and to use the -values option to update the property.

**Comment by gautamdsheth** [comment]
Ok, sure. Will keep it open, let me know what MS responds to this , we can merge it later then.
Thanks :)

**Comment by reshmee011** [comment]
It seems to be able to set the field as non crawlable, the "SharePoint Server Publishing Infrastructure" has to be activated which is not a recommended solution , hence closing the PR.

**Comment by reshmee011** [comment]
It seems to be able to set the field as non crawlable, the "SharePoint Server Publishing Infrastructure" has to be activated which is not a recommended solution , hence closing the PR.

**Pull request closed without merging**
