### PR TITLE
Feature #1580, Docker Image

### PR DESCRIPTION
**Pull request by shurick81**
## Type ##
- [ ] Bug Fix
- [x] New Feature
- [ ] Sample

## Related Issues? ##
Completes #1580

## What is in this Pull Request ? ##
Docker image with PnP.PowerSshell is published to Docker Hub

### CODE REVIEW

**Comment by gautamdsheth** [comment]
hi @shurick81 , looks like amazing stuff !

Looked at your PR and had a few questions:

1) You modified the release pipeline, is it so that everytime we publish the nightly, it will also publish to Docker ?

2) It requires a Docker user name and password, so do create it in docker and then create the secret in our repository with those values ? 

3) Do we need to create an account on docker before we can publish this image ? 

4) Is it free or we need to pay some amount for publishing ? 

Sorry , dont have a clue about docker. Also, please correct me if the questions or their premise is wrong :)

**Comment by shurick81** [comment]
Hi @gautamdsheth, thanks for finding time for reviewing this commit.

Here are short answers on the questions :)

1. yes
2. I already talked to Koen and Waldek, so the variables with user name and password are already in place for this Github project
3. No need to create a new account because there is already account that we can use
4. As far as I know, we don't need to pay anything extra but it should be probably Waldek who is aware of the specific Docker plan we are using

**Comment by shurick81** [comment]
I just realized that the description of this PR was pointing a wrong issue (1589 instead of 1580). Now corrected the description.

By the way, what is our next step regarding this PR?

**Comment by erwinvanhunen** [comment]
@shurick81: can you explain the use of the release.yml action/workflow? I see the addition to the nightlyrelease workflow, but I do not see easily what the release.yml one is doing?

**Comment by shurick81** [comment]
Hi @erwinvanhunen, let me put it like this.

This is what we now have in https://github.com/pnp/powershell:

| Release Type | Module Build in Pipeline | Publishing to the PS Gallery in Pipeline | Publishing to the Docker Hub in Pipeline | Pipeline |
| - | - | - | - | - |
| Nightly Releases | :white_check_mark: | :white_check_mark: | :white_large_square: | nightlyrelease.yml |
| Supported Releases | :white_large_square: | :white_large_square: | :white_large_square: | #N/A |

Here's what I offer in PR:

| Release Type | Module Build in Pipeline | Publishing to the PS Gallery in Pipeline | Publishing to the Docker Hub in Pipeline | Pipeline |
| - | - | - | - | - |
| Nightly Releases | :white_check_mark: | :white_check_mark: | :white_check_mark: | nightlyrelease.yml |
| Supported Releases | :white_large_square: | :white_large_square: | :white_check_mark: | release.yml |

Later on there will be opportunity to put more things in release.yml. Does it make sense?

**Comment by shurick81** [comment]
I have also added user documentation, here's how it looks on the Docker Hub: https://hub.docker.com/r/asapozhkov/powershell.
It should be copied manually from the md document: https://raw.githubusercontent.com/alexsapozhkov/powershell/dev/docker/hub.docker.md.

I also added a few lines here: https://github.com/alexsapozhkov/powershell/blob/dev/pages/index.md

**Comment by gautamdsheth** [comment]
@shurick81 - much clearer thanks !!

What I didnt understand about the release action(release.yml)  is the CRON value.

Why are you releasing it everyday at 3:30 ? Did you mean it every 30 days or something ? Unless I am completely mistaken.
The thing is, we dont have a fixed release cadence, however much we would like to unfortunately :( 

So, major release usually happens every 2-3 months and we dont have a fixed date/time for it. 
Can you please change it a manual one instead ? I will try to trigger it at every release

**Comment by shurick81** [comment]
Hi @gautamdsheth, the logic behind is that this job that we can run daily is smart enough and it is identifying those versions of the module that are published in PS Gallery but not published yet in Docker Hub. So it should be fine to run it automatically and it will eventually publish a new module version. However, if you want to run it manually anyway, there is no problem, I can remove the CRON value.

**Comment by gautamdsheth** [comment]
Thank you @shurick81 , have merged the PR !
Looks great !

One request though :) 

If you have some time, could be also please write an article (100 level) on how to go about using this ? Basic stuff for people new to Docker and all .

You can write it in markdown and add it here ? 

https://github.com/pnp/powershell/tree/dev/pages/articles 

This is a request, you can totally ignore it :) 

Also, if you are interested, would you like to demo it in a PnP Community call, would love to see it in action  ? We can help with that.

Thank you so much again for the amazing work 🙏😊

**Comment by shurick81** [comment]
Hi @gautamdsheth we already have some documentation here: https://pnp.github.io/powershell/. But probably we could mention that before using this Docker image, one needs to have Docker engine installed?

**Pull request merged**
