### PR TITLE
Closes #3744 and #3753

### LINKED ISSUE #3744: [BUG]: Get-PnPUnifiedAuditLog -ContentType DLP throwing 401 error
### Reporting an Issue or Missing Feature

Get-PnPUnifiedAuditLog -ContentType DLP throws the error 
 Unauthorized (401): The permission set (ActivityFeed.Read ServiceHealth.Read) sent in the request does not include the expected permission.    

### Expected behavior 
The cmdlet to be successful

### Actual behavior 
Error 401 thrown
 Unauthorized (401): The permission set (ActivityFeed.Read ServiceHealth.Read) sent in the request does not include the expected permission.    

### Steps to reproduce behavior
$SiteUrl = "https://reshmeeauckloo.sharepoint.com/"
Connect-PnPOnline -url $siteurl -Interactive
Get-PnPUnifiedAuditLog -ContentType DLP 

Upon some investigation, found out connecting with entra app with missing permissions threatintelligence and activity reports, I could not reproduce the issue anymore.
image

### What is the version of the Cmdlet module you are running?
2.3.37  

Please assign to me.

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows

### PR DESCRIPTION
**Pull request by reshmee011**
## Type ##
- [ ] Bug Fix

## Related Issues? ##
Fixes #3744 

## What is in this Pull Request ? ##
updated permissions in file src\Commands\Resources\O365ManagementPermissions.json to include these two

{
            "adminConsentDescription": "Allows the application to read service health information for your organization.",
            "adminConsentDisplayName": "Read activity reports for your organization",
            "id": "b3b78c39-cb1d-4d17-820a-25d9196a800e",
            "isEnabled": true,
            "isAdmin": true,
            "consentDescription": "Allows the application to read service health information for your organization.",
            "consentDisplayName": "Read service health information for your organization",
            "value": "ActivityReports.Read"
        },
        {
            "adminConsentDescription": "Allows the application to read threat intelligence data for your organization",
            "adminConsentDisplayName": "Read threat intelligence data for your organization",
            "id": "17f1c501-83cd-414c-9064-cd10f7aef836",
            "isEnabled": true,
            "isAdmin": true,
            "consentDescription": "Allows the application to read threat intelligence data for your organization",
            "consentDisplayName": "Read threat intelligence data for your organization",
            "value": "ThreatIntelligence.Read"
        }

### CODE REVIEW

**Comment by gautamdsheth** [comment]
@reshmee011 - should we update the cmdlet permissions as well for this ? Also, I think we need to mention it in the docs as well.

**Comment by reshmee011** [comment]
@gautamdsheth , it's quite interesting as I could not find any documentation on these two extra permissions from the o365 management APIs and they can't be added to the app registration from the UI except updating the manifest json to include these extra permissions. 
Where shall I mention it in the docs? It is worth mentioning it.
image

**Comment by gautamdsheth** [comment]
@reshmee011 - I meant in the cmdlet , we have requiredminimalpermissions attribute, maybe we can add it there ? 

In the cmdlet docs as well something similar maybe ?

**Comment by reshmee011** [comment]
@gautamdsheth : I have added the permissions to the cmd and doc. At least adding these extra permissions helps with the unauthorized bug I was facing, hope it will be the same for others.

**Comment by gautamdsheth** [comment]
Awesome, thanks @reshmee011 merged it !!

**Pull request merged**
